### Задание 1

In [1]:
import numpy as np

In [8]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Задание 2

In [10]:
a.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
a.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [15]:
a.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### Задание 3

In [18]:
a.reshape(2, -1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
a.reshape(3, -1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [23]:
a.reshape(-1, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [35]:
a.reshape(-1, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### Задание 4

In [38]:
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
# Нет

### Задание 5

In [44]:
a5 = np.random.normal(0, 1.0 ,(3, 4))
a5

array([[ 1.64776579,  0.74641058, -1.82416684,  0.83804072],
       [-0.96115104, -1.21493893, -1.45084791, -1.03194501],
       [-0.12579585,  1.3013576 ,  1.40925127,  0.62496989]])

In [45]:
a5.size

12

In [50]:
a51 = a5.flatten()
a51

array([ 1.64776579,  0.74641058, -1.82416684,  0.83804072, -0.96115104,
       -1.21493893, -1.45084791, -1.03194501, -0.12579585,  1.3013576 ,
        1.40925127,  0.62496989])

In [51]:
a51.size

12

### Задание 6

In [59]:
a = np.arange(20, 0, -2)
a

10

### Задание 7

In [61]:
b = np.arange(20, 1, -2).reshape(1, -1)
b
# a от b не отличаются, в обоих случаях одномерный массив - 1 строка

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

### Задание 8

In [76]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [77]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [78]:
np.concatenate((a, b), axis=0)

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Задание 9

In [82]:
a = np.arange(0, 12, 1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [87]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [94]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [93]:
# Размер 4х4
B.size

16

In [96]:
# Обратную матрицу вычислить не получится, так как определитель равен 0
D = np.linalg.det(B)
D

0.0

### Задание 10

In [101]:
np.random.RandomState(seed=42)

RandomState(MT19937) at 0x7F4FD89E7AF0

### Задание 11

In [108]:
c = 16 * np.random.sample((1, 16))
c

array([[ 7.70610008, 13.23600381,  6.2363899 , 12.99981153,  2.92839653,
         4.58817185, 15.74090989, 11.10477954,  8.45003504,  6.11004095,
         2.46399133, 13.27838697,  3.24779811,  8.2600845 ,  9.0746209 ,
         1.66386998]])

### Задание 12

In [112]:
C = c.reshape(4, -1)
C

array([[ 7.70610008, 13.23600381,  6.2363899 , 12.99981153],
       [ 2.92839653,  4.58817185, 15.74090989, 11.10477954],
       [ 8.45003504,  6.11004095,  2.46399133, 13.27838697],
       [ 3.24779811,  8.2600845 ,  9.0746209 ,  1.66386998]])

In [114]:
D = C + B * 10
D

array([[  57.70610008,  153.23600381,  236.2363899 ,  332.99981153],
       [ 142.92839653,  504.58817185,  875.74090989, 1231.10477954],
       [ 238.45003504,  866.11004095, 1492.46399133, 2133.27838697],
       [ 323.24779811, 1228.2600845 , 2129.0746209 , 3021.66386998]])

In [115]:
np.linalg.det(D)

8402844.88440674

In [116]:
np.linalg.matrix_rank(D)

4

In [118]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.01285565,  0.06787398,  0.05095757, -0.06221266],
       [ 0.07356902, -0.09048543, -0.05943759,  0.07072113],
       [-0.01950645,  0.07403844, -0.039126  , -0.00039276],
       [-0.01478511, -0.02264773,  0.04627751, -0.02148407]])

### Задание 13

In [123]:
D_inv = np.where(D_inv > 0, 1, 0)
D_inv

array([[0, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [124]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [125]:
C

array([[ 7.70610008, 13.23600381,  6.2363899 , 12.99981153],
       [ 2.92839653,  4.58817185, 15.74090989, 11.10477954],
       [ 8.45003504,  6.11004095,  2.46399133, 13.27838697],
       [ 3.24779811,  8.2600845 ,  9.0746209 ,  1.66386998]])

In [126]:
E = np.where(D_inv == 1, B, C)
E

array([[  7.70610008,  14.        ,  23.        ,  12.99981153],
       [ 14.        ,   4.58817185,  15.74090989, 122.        ],
       [  8.45003504,  86.        ,   2.46399133,  13.27838697],
       [  3.24779811,   8.2600845 , 212.        ,   1.66386998]])